use ExtUtils::MakeMaker;

# TODO: read deplist.txt (OpenShift style)
my %deplist = ();

WriteMakefile(
    PREREQ_PM => {
        %deplist,
        'Plack::Handler::Starman' => 0,

        # Comment out if you need HTTPS
        # 'Crypt::OpenSSL::Random'   => 0.04,

        # Comment out if you use TemplateToolkit
        # 'Template' => 0,

        # Add your dependencies here
     }
);
